language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - composer install

script:
  - ./vendor/bin/phpstan analyse src tests --level=7
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/
